# Generated by Django 5.1.1 on 2024-11-07 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobanner',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InfoBannerContent',
        ),
    ]
