# Generated by Django 5.1.1 on 2024-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_arrival', models.BooleanField()),
                ('airline', models.CharField(max_length=50)),
                ('flight_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
