# Generated by Django 5.1.1 on 2024-11-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flight',
            table='schedule',
        ),
    ]
