# Generated by Django 5.1.1 on 2024-11-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['-time']},
        ),
    ]
