# Generated by Django 5.1.1 on 2024-11-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={},
        ),
    ]
