# Generated by Django 5.1.1 on 2025-04-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_flight_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='city',
            new_name='arrival_city',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_city_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_city_kg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
