# Generated by Django 5.1.1 on 2025-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('jewelry', 'Ювелирка'), ('dutyfree', 'Duty-free'), ('souvenirs', 'Сувениры'), ('simcard', 'SIM-card')], max_length=10),
        ),
    ]
