# Generated by Django 5.1.1 on 2025-04-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_service_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="service_images/"),
        ),
    ]
