# Generated by Django 5.1.1 on 2025-04-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (английский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ky',
            field=models.TextField(blank=True, verbose_name='Описание (кыргызский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (русский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (английский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (кыргызский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(default='Default Service Name', max_length=100, verbose_name='Название (русский)'),
            preserve_default=False,
        ),
    ]
