# Generated by Django 5.1.1 on 2025-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_description_remove_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Локация (английский)'),
        ),
        migrations.AddField(
            model_name='service',
            name='location_ky',
            field=models.CharField(blank=True, max_length=100, verbose_name='Локация (кыргызский)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Локация (русский)'),
        ),
    ]
